### ISSUE TITLE
Use a different css selector

### ISSUE THREAD

**Issue by sangjunp4rk** [ankit6889/Dasmoto#3]
Use a css selector other than 'p' for unique text like bold or highlighting. For example, next time make sure to use and specify span. For example, do `<span class = “prices” >`. This makes your code more flexible as it grows in the future and you have to use span elsewhere. This way you can use it elsewhere if you just specify another class.

https://github.com/ankit6889/Dasmoto/blob/master/index.html#L19

**Comment by ankit6889** [comment]
not clear on the concept of the span. will redo after having AN understanding clearly.
